<?php

/**
 * @file
 * Primary module hooks for storizborn_surcharger module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */
/**
 * implement hook_preprocess_HOOK
 */

function storizborn_surcharger_preprocess_block__aggregator(&$vars){
  // surcharge des élément pour le template
  $vars['list'] = $vars['element']['content']['list'];
  $vars['items'] = $vars['element']['content']['list']['#items'];
	dump($vars['list']);

}