<?php

/**
 * @file
 * Primary module hooks for storizborn_surcharger module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */
/**
 * implement hook_preprocess_HOOK
 */

function storizborn_surcharger_preprocess_block__aggregator(){
   // surcharge des élément pour le template
   $hooks['storizborn_surcharger_agregator_theme'] = [
    'render element' => 'element',
    'preprocess functions' => [
      'template_preprocess_storizborn_surcharger_agregator_theme'
    ],
    'file' => 'stroizborn_surcharger.theme.inc'
  ];
}